services:
  db:
    image: postgres:14
    volumes:
      - ../shared/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: furima_production
      TZ: Asia/Tokyo
    env_file:
      - /var/www/furima/shared/.env
    networks:
      - furima-net

  web:
    build:
      context: .
      args:
        RAILS_ENV: production
    volumes:
      - .:/app
      - /var/www/furima/shared/config/database.yml:/app/config/database.yml:ro
      - /var/www/furima/shared/public/assets:/app/public/assets
      - ../shared/storage:/app/storage
      - /app/tmp
    environment:
      TZ: Asia/Tokyo
    env_file:
      - /var/www/furima/shared/.env
    depends_on:
      - db
    networks:
      - furima-net
    ports:
      - "3000:3000"

  nginx:
    image: nginx:stable-alpine
    ports: []
    volumes:
      - /var/www/furima/shared/nginx/conf.d:/etc/nginx/conf.d:ro
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - web
    networks:
      - furima-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    environment:
      - CLOUDFLARED_TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
    depends_on:
      - nginx
    env_file:
      - /var/www/furima/shared/.env
    networks:
      - furima-net

volumes:
  postgres-data:

networks:
  furima-net:
