default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password: yourpassword
  host: db
  database: furima-41768_rails7_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password: yourpassword
  host: db
  database: furima-41768_rails7_test

production:
  <<: *default
  adapter: postgresql
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: db
  database: furima_production